### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by alu0101205908** [ULL-ESIT-INF-DSI-2021/ull-esit-inf-dsi-20-21-prct07-menu-datamodel-grupo-q#1]
Buenas tardes

Tenemos una duda acerca de las interfaces que utilizamos. Cuando definimos una interfaz (como vimos en clase), esta debería de tener los métodos y propiedades que tuviera la clase que implemente esa interfaz. El problema está en que si definimos en una interfaz las propiedades siempre van a ser públicas, y esto no nos interesa. Por lo que vimos en un foro, se podría definir en la interfaz los métodos getter y setter (para acceder a esas propiedades), y de esa manera esos métodos van a ser públicos, mientras que en la clase podemos definir las propiedades como privadas o protegidas. Nos preguntábamos si lo podemos implementar de esta manera o sería una mala práctica.

Saludos y muchas gracias de antemano.

@esegredo @amarrerod @lgforte

**Comment by amarrerod** [comment]
La buena práctica es esa, definir como protegido o privado todo aquello de la clase que no se deba acceder desde el exterior. Y para acceder a esas propiedades, usar los getters y setters correspondientes. **Definirlo todo como público por comodidad es una muy mala práctica.** 

De todas formas, las Interfaces no tienen por qué tener todas las propiedades y métodos de una clase, solo las que deben tener todos los objetos de las clases que implementan esa interfaz. Quizás es mejor definir las propiedades en la clase como privadas y crear los getters y setters. Dejaríamos en la interfaz únicamente los métodos con más 'lógica', los necesarios que debe implementar la clase.  Intenten mantener las interfaces y clases lo más concretas posible siguiendo el principio de responsabilidad única.

**Comment by alu0101205908** [comment]
Recibido, muchas gracias.
