### ISSUE TITLE
Carta

### ISSUE THREAD

**Issue by alu0101206479** [ULL-ESIT-INF-DSI-2021/ull-esit-inf-dsi-20-21-prct07-menu-datamodel-grupo-q#2]
Buenas, no nos termina de quedar claro que es Carta, si es una clase, que tiene un atributo Platos[] y otro atributo Menus[], o es simplemente una prueba en la que se crean distintos objetos Platos y distintos objetos Menus. Muchas gracias y espero su respuesta.

@esegredo  @amarrerod  @lgforte

**Comment by esegredo** [comment]
Yo lo diseñaría teniendo en cuenta la primera de las opciones que comentan.

**Comment by alu0101203003** [comment]
Buenas, según pone en el enunciado de la práctica (en el apartado de Menús), se debe poder consultar el listado de grupos de alimentos por orden de aparición. No entendemos si se refiere a que la funcion getListadoGrupos imprima el listado, o devuelva un vector con el listado. Nos surge la misma duda también para la lista de alimentos y/o ingredientes que componen los platos.

Un saludo y gracias de antemano.

@esegredo @amarrerod @lgforte

**Comment by esegredo** [comment]
Hola @alu0101203003

Como norma general, es una buena práctica que todos los métodos de una clase o funciones que tengas definidas en tu código devuelvan un valor, salvo las que llevan a cabo alguna funcionalidad y no deben retornar nada o void. Teniendo en cuenta lo anterior, lo que yo haría es que mis métodos y funciones devolvieran, por ejemplo, un listado de los grupos, alimentos o ingredientes y, luego, donde toque, utilizar los listados para imprimirlos.

Espero haberles ayudado.

Saludos.
